version: 1
builder:
  configs:
    - platform_compatibility:
        - macos
      documentation_targets:
        - SwiftDataFrame
        - SwiftStats
        - SwiftPreprocessing
        - SwiftML
        - SwiftCluster
        - SwiftNLP
        - SwiftOptimize
        - SwiftForecast
        - SwiftLLM
        - SwiftExplain
        - SwiftVisualization
        - SwiftVision
        - SwiftDatabase
        - SwiftAgent
    - platform_compatibility:
        - ios
        - visionos
      documentation_targets:
        - SwiftDataFrame
        - SwiftStats
        - SwiftNLP
        - SwiftForecast
        - SwiftVisualization
        - SwiftDatabase
