import Foundation

/// Options configuring generative text inference.
public struct LLMOptions: Sendable {
    /// The temperature.
    public var temperature: Double
    /// The top p.
    public var topP: Double
    /// The top k.
    public var topK: Int
    /// The max tokens.
    public var maxTokens: Int
    
    /// Creates a new instance.
    /// - Parameters:
    ///   - temperature: The temperature.
    ///   - topP: The top p.
    ///   - topK: The top k.
    ///   - maxTokens: The max tokens.
    public init(
        temperature: Double = 0.7,
        topP: Double = 0.9,
        topK: Int = 40,
        maxTokens: Int = 100
    ) {
        self.temperature = temperature
        self.topP = topP
        self.topK = topK
        self.maxTokens = maxTokens
    }
}

/// A protocol representing a local large language model.
public protocol LLMModel: Sendable {
    /// Generates tokens asynchronously in a stream.
    /// - Parameters:
    ///   - prompt: The starting text prompt.
    ///   - options: Configuration options for generation.
    /// - Returns: An AsyncStream of string segments generated by the model.
    func generate(prompt: String, options: LLMOptions) async throws -> AsyncStream<String>
}
