#if os(macOS)
import Foundation
import MLX
import MLXNN
import SwiftNLP

/// A basic local Decoder-only Transformer model using MLX.
public class TransformerDecoder: Module, @unchecked Sendable {
    /// The embedding.
    public let embedding: Embedding
    /// The pos embedding.
    public let posEmbedding: Embedding
    /// The attention.
    public let attention: MultiHeadAttention
    /// The norm.
    public let norm: RMSNorm
    /// The output projection.
    public let outputProjection: Linear
    
    /// The tokenizer.
    public let tokenizer: any Tokenizer
    /// The dimensions.
    public let dimensions: Int
    /// The max seq len.
    public let maxSeqLen: Int
    
    /// Initializes the Transformer Decoder model.
    /// - Parameters:
    ///   - vocabSize: The size of the token vocabulary.
    ///   - tokenizer: The tokenizer to convert text to/from token IDs.
    ///   - dimensions: The model dimensionality.
    ///   - numHeads: The number of attention heads.
    ///   - maxSeqLen: The maximum sequence length supported.
    public init(
        vocabSize: Int,
        tokenizer: any Tokenizer,
        dimensions: Int = 128,
        numHeads: Int = 4,
        maxSeqLen: Int = 256
    ) {
        self.tokenizer = tokenizer
        self.dimensions = dimensions
        self.maxSeqLen = maxSeqLen
        
        self.embedding = Embedding(embeddingCount: vocabSize, dimensions: dimensions)
        self.posEmbedding = Embedding(embeddingCount: maxSeqLen, dimensions: dimensions)
        self.attention = MultiHeadAttention(dimensions: dimensions, numHeads: numHeads)
        self.norm = RMSNorm(dimensions: dimensions)
        self.outputProjection = Linear(dimensions, vocabSize, bias: false)
        
        super.init()
    }
    
    /// Executes the forward pass of the model.
    /// - Parameter x: An MLXArray of token IDs, shape [seq_len] or [batch, seq_len].
    /// - Returns: Logits tensor, shape [batch, seq_len, vocab_size].
    public func callAsFunction(_ x: MLXArray) -> MLXArray {
        var input = x
        if input.ndim == 1 {
            input = input.expandedDimensions(axis: 0) // shape [1, seq_len]
        }
        
        let seqLen = input.shape[1]
        
        // 1. Token Embeddings
        let hEmbed = embedding(input)
        
        // 2. Position Embeddings
        let positions = MLXArray(0..<seqLen)
        let hPos = posEmbedding(positions)
        
        var h = hEmbed + hPos
        
        // 3. Self Attention Block
        let mask = MultiHeadAttention.createAdditiveCausalMask(seqLen)
        let attended = attention(h, keys: h, values: h, mask: mask)
        
        // Residual connection & RMSNorm
        h = norm(h + attended)
        
        // 4. Output logits projection
        return outputProjection(h)
    }
    
    /// Generates tokens asynchronously in a stream.
    /// - Parameters:
    ///   - prompt: The starting text prompt.
    ///   - options: Configuration options for generation.
    /// - Returns: An AsyncStream of string segments generated by the model.
    public func generate(prompt: String, options: LLMOptions) async throws -> AsyncStream<String> {
        let tokenizer = self.tokenizer
        let maxSeqLen = self.maxSeqLen
        
        return AsyncStream<String> { continuation in
            let task = Task {
                var tokens = tokenizer.encode(text: prompt)
                if tokens.isEmpty {
                    tokens = [0] // Fallback to unknown token if empty
                }
                
                for _ in 0..<options.maxTokens {
                    if Task.isCancelled { break }
                    
                    // Constrain input to maximum sequence length
                    let inputTokens = Array(tokens.suffix(maxSeqLen))
                    let arrayInput = MLXArray(inputTokens)
                    
                    // Forward pass: logits shape [1, seq_len, vocab_size]
                    let logits = self(arrayInput)
                    
                    // Extracted logits for the last token in sequence: shape [vocab_size]
                    let lastLogits = logits[0, logits.shape[1] - 1]
                    
                    // Sample next token ID
                    let nextToken = Sampler.sample(logits: lastLogits, options: options)
                    
                    let decodedToken = tokenizer.decode(tokens: [nextToken])
                    
                    if decodedToken.isEmpty || decodedToken == "<unk>" {
                        break
                    }
                    
                    continuation.yield(decodedToken)
                    tokens.append(nextToken)
                }
                continuation.finish()
            }
            
            continuation.onTermination = { _ in
                task.cancel()
            }
        }
    }

    /// Generates tokens asynchronously in an error-throwing stream (`AsyncThrowingStream`).
    /// - Parameters:
    ///   - prompt: The starting text prompt.
    ///   - options: Configuration options for generation.
    /// - Returns: An AsyncThrowingStream of string tokens.
    public func generateStream(prompt: String, options: LLMOptions) -> AsyncThrowingStream<String, any Error> {
        let tokenizer = self.tokenizer
        let maxSeqLen = self.maxSeqLen
        
        return AsyncThrowingStream<String, any Error> { continuation in
            let task = Task {
                var tokens = tokenizer.encode(text: prompt)
                if tokens.isEmpty {
                    tokens = [0]
                }
                
                for _ in 0..<options.maxTokens {
                    if Task.isCancelled { break }
                    
                    let inputTokens = Array(tokens.suffix(maxSeqLen))
                    let arrayInput = MLXArray(inputTokens)
                    let logits = self(arrayInput)
                    let lastLogits = logits[0, logits.shape[1] - 1]
                    let nextToken = Sampler.sample(logits: lastLogits, options: options)
                    let decodedToken = tokenizer.decode(tokens: [nextToken])
                    
                    if decodedToken.isEmpty || decodedToken == "<unk>" {
                        break
                    }
                    
                    continuation.yield(decodedToken)
                    tokens.append(nextToken)
                }
                continuation.finish()
            }
            
            continuation.onTermination = { _ in
                task.cancel()
            }
        }
    }
}
#endif // os(macOS)

